package auditoria.logica.servicios;

import accesoDatos.AccesoDatos;
import auditoria.logica.entidades.APredios;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import master.logica.entidades.Usuario;
import master.logica.servicios.ServiciosUsuario;

public class FAPredios {

    public static ArrayList<APredios> obtenerAuditoriaPredios() throws Exception {
        ArrayList<APredios> lst = new ArrayList<>();
        AccesoDatos accesoDatos;
        PreparedStatement prstm;
        APredios predio;
        ResultSet resultSet;
        String sql;
        try {
            accesoDatos = new AccesoDatos();
            sql = "SELECT * from auditoria.f_seleccionar_predios()";
            resultSet = accesoDatos.ejecutaQuery(sql);
            while (resultSet.next()) {
                predio = new APredios();
                predio.setTitularDomi(new Usuario());
                predio.setRepreLegal(new Usuario());
                predio.setUsuarioSistema(new Usuario());

                predio.setIdAudPredios(resultSet.getInt("sr_id_aud_predio"));
                predio.setIdPredio(resultSet.getInt("int_id_predio"));
                predio.setNumFicha(resultSet.getInt("int_num_ficha"));
                predio.setIdParroquia(resultSet.getInt("int_id_parroquia"));
                predio.setZona(resultSet.getInt("int_zona"));
                predio.setSector(resultSet.getInt("int_sector"));
                predio.setManzana(resultSet.getInt("int_manzana"));
                predio.setNumPredio(resultSet.getInt("int_num_predio"));
                predio.setProHorBloque(resultSet.getInt("int_prop_hor_bloque"));
                predio.setPropHorPiso(resultSet.getInt("int_prop_hor_piso"));
                predio.setPropHorUnidad(resultSet.getInt("int_prop_hor_unidad"));
                predio.setClaveCatastral(resultSet.getString("chv_clave_catastral"));
                predio.setClaveCatastralAnt(resultSet.getString("chv_clave_catastral_ant"));
                predio.setBarrio(resultSet.getString("chv_barrio"));
                predio.setCallePrincipal(resultSet.getString("chv_calle_princ"));
                predio.setCalleSecundaria(resultSet.getString("chv_calle_secund"));
                predio.setNumCasa(resultSet.getString("chv_num_casa"));
                predio.setNombreEdificio(resultSet.getString("chv_nombre_edificio"));
                predio.setTitularDomi(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("int_id_titular_dom")));
                predio.setRepreLegal(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("int_id_rep_legal")));
                predio.setDominio(resultSet.getInt("int_id_dominio"));
                predio.setCondicion(resultSet.getString("chv_condicion"));
                predio.setFormaAdquisicion(resultSet.getString("chv_forma_adq"));
                predio.setNotaria(resultSet.getString("chv_notaria"));
                predio.setFechaTituloProp(resultSet.getDate("dt_fecha_titulo_prop"));
                predio.setFechaRegistro(resultSet.getDate("dt_fecha_registro"));
                predio.setAreaEscritura(resultSet.getDouble("db_area_escritura"));
                predio.setProAnterior(resultSet.getString("chv_prop_anterior"));
                predio.setAvaluoPropi(resultSet.getDouble("db_avaluo_prop"));
                predio.setGestUsoSuelo(resultSet.getString("chv_gest_uso_suelo"));
                predio.setUsoSueloConsumo(resultSet.getString("chv_uso_suelo_consumo"));
                predio.setUsoSueloIntercambio(resultSet.getString("chv_us_suel_intercambio"));
                predio.setUsoSueloProduc(resultSet.getString("chv_us_suel_produc"));
                predio.setOcupacionPredio(resultSet.getString("chv_ocupacion_predio"));
                predio.setLocalizacionPredio(resultSet.getString("chv_localizacion_predio"));
                predio.setTopografiaPredio(resultSet.getString("chv_topografia_pedio"));
                predio.setFormaPredio(resultSet.getString("chv_forma_predio"));
                predio.setCaracteristicasSuelo(resultSet.getString("chv_caract_suelo"));
                predio.setUsoVias(resultSet.getString("chv_uso_vias"));
                predio.setMaterialVia(resultSet.getString("chv_material_vias"));
                predio.setRedAgua(resultSet.getString("chv_red_agua"));
                predio.setAlcantarillado(resultSet.getString("chv_alcantarillado"));
                predio.setEnergiaElectrica(resultSet.getString("chv_energ_electric"));
                predio.setRedTelefono(resultSet.getString("chv_red_telefon"));
                predio.setRecoleBasura(resultSet.getString("chv_rec_basura"));
                predio.setTransportePublico(resultSet.getString("chv_transp_publico"));
                predio.setInternet(resultSet.getString("chv_internet"));
                predio.setOtrosServicios(resultSet.getString("chv_otros_servicios"));
                predio.setAreaConstruccion(resultSet.getDouble("db_area_construc"));
                predio.setAreaTotalConstruccion(resultSet.getDouble("db_area_total_const"));
                predio.setAreaTotalTerreno(resultSet.getDouble("db_area_total_terreno"));
                predio.setPatio(resultSet.getString("chv_patio"));
                predio.setPiscina(resultSet.getString("chv_piscina"));
                predio.setCerramiento(resultSet.getString("chv_cerramiento"));
                predio.setCisterna(resultSet.getString("chv_cisterna"));
                predio.setMuros(resultSet.getString("chv_muros"));
                predio.setAscensor(resultSet.getString("chv_ascensor"));
                predio.setNumBanios(resultSet.getInt("int_num_banios"));
                predio.setLinderoFrente1(resultSet.getDouble("db_lindero_frente1"));
                predio.setLinderoFrente2(resultSet.getDouble("db_lindero_frente2"));
                predio.setLinderoFrente3(resultSet.getDouble("db_lindero_frente3"));
                predio.setLinderoFrente4(resultSet.getDouble("db_lindero_frente4"));
                predio.setLinderoCalle1(resultSet.getString("chv_lindero_calle1"));
                predio.setLinderoCalle2(resultSet.getString("chv_lindero_calle2"));
                predio.setLinderoCalle3(resultSet.getString("chv_lindero_calle3"));
                predio.setLinderoCalle4(resultSet.getString("chv_lindero_calle4"));
                predio.setLinderoAlicuota1(resultSet.getDouble("db_lindero_alicuota1"));
                predio.setLinderoAlicuota2(resultSet.getDouble("db_lindero_alicuota2"));
                predio.setLinderoAlicuota3(resultSet.getDouble("db_lindero_alicuota3"));
                predio.setLinderoAlicuota4(resultSet.getDouble("db_lindero_alicuota4"));
                predio.setDerechosAcciones(resultSet.getDouble("db_derechos_acciones"));
                predio.setCroquis(resultSet.getString("chv_croquis"));
                predio.setEmplazamiento(resultSet.getString("chv_emplazamiento"));
                predio.setFotografia(resultSet.getString("chv_fotografia"));
                predio.setTopografiaRefTop(resultSet.getString("chv_topografia_ref_top"));
                predio.setFotoAerea(resultSet.getString("chv_foto_aerea"));
                predio.setOtraRefTopo(resultSet.getString("chv_otra_ref_top"));
                predio.setCoordE(resultSet.getDouble("db_coord_e"));
                predio.setCoordN(resultSet.getDouble("db_coord_n"));
                predio.setColindanteNorte(resultSet.getString("chv_colindant_nort"));
                predio.setColindanteEste(resultSet.getString("chv_colindant_este"));
                predio.setColindanteSur(resultSet.getString("chv_colindant_sur"));
                predio.setColindanteOeste(resultSet.getString("chv_colindant_oest"));
                predio.setFuenteInformacion(resultSet.getString("chv_fuente_informant"));
                predio.setTelefoInformacion(resultSet.getString("chv_telf_informant"));
                predio.setFichaAdjunta(resultSet.getString("chv_ficha_adjunta"));
                predio.setFechaRegistrada(resultSet.getTimestamp("ts_fecha_registro"));
                predio.setFechaActualizacion(resultSet.getTimestamp("ts_fecha_actualizacion"));
                predio.setFechaBaja(resultSet.getTimestamp("ts_fecha_baja"));
                predio.setEstadoLogico(resultSet.getString("ch_estado_logico"));
                predio.setPorcentaExcepsion(resultSet.getDouble("db_porcent_excep"));
                predio.setExcepsionEsp(resultSet.getString("chv_excencion_esp"));
                predio.setObservaciones(resultSet.getString("chv_observaciones"));
                predio.setSectorHomogeneo(resultSet.getInt("id_sector_homogeneo"));
                predio.setUsuarioSistema(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("id_session_usuario")));
                predio.setFechaModificacion(resultSet.getTimestamp("ts_fecha_creacion"));
                predio.setHoraModificacion(resultSet.getTime("tm_hora_creacion"));
                predio.setAccionRealizada(resultSet.getString("chv_accion_realizada"));
                lst.add(predio);

            }
        } catch (Exception e) {
            throw e;
        }

        return lst;
    }

    public static ArrayList<APredios> comparacionPredios(int codigoPredio) throws Exception {
        ArrayList<APredios> lst = new ArrayList<>();
        AccesoDatos accesoDatos;
        PreparedStatement prstm;
        APredios predio;
        ResultSet resultSet;
        String sql;
        try {
            accesoDatos = new AccesoDatos();
            sql = "select * from auditoria.f_seleccionar_predios_dado_id(?)";
            prstm = accesoDatos.creaPreparedSmt(sql);
            prstm.setInt(1, codigoPredio);
            resultSet = accesoDatos.ejecutaPrepared(prstm);
            while (resultSet.next()) {
                predio = new APredios();
                predio.setTitularDomi(new Usuario());
                predio.setRepreLegal(new Usuario());
                predio.setUsuarioSistema(new Usuario());

                predio.setIdAudPredios(resultSet.getInt("sr_id_aud_predio"));
                predio.setIdPredio(resultSet.getInt("int_id_predio"));
                predio.setNumFicha(resultSet.getInt("int_num_ficha"));
                predio.setIdParroquia(resultSet.getInt("int_id_parroquia"));
                predio.setZona(resultSet.getInt("int_zona"));
                predio.setSector(resultSet.getInt("int_sector"));
                predio.setManzana(resultSet.getInt("int_manzana"));
                predio.setNumPredio(resultSet.getInt("int_num_predio"));
                predio.setProHorBloque(resultSet.getInt("int_prop_hor_bloque"));
                predio.setPropHorPiso(resultSet.getInt("int_prop_hor_piso"));
                predio.setPropHorUnidad(resultSet.getInt("int_prop_hor_unidad"));
                predio.setClaveCatastral(resultSet.getString("chv_clave_catastral"));
                predio.setClaveCatastralAnt(resultSet.getString("chv_clave_catastral_ant"));
                predio.setBarrio(resultSet.getString("chv_barrio"));
                predio.setCallePrincipal(resultSet.getString("chv_calle_princ"));
                predio.setCalleSecundaria(resultSet.getString("chv_calle_secund"));
                predio.setNumCasa(resultSet.getString("chv_num_casa"));
                predio.setNombreEdificio(resultSet.getString("chv_nombre_edificio"));
                predio.setTitularDomi(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("int_id_titular_dom")));
                predio.setRepreLegal(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("int_id_rep_legal")));
                predio.setDominio(resultSet.getInt("int_id_dominio"));
                predio.setCondicion(resultSet.getString("chv_condicion"));
                predio.setFormaAdquisicion(resultSet.getString("chv_forma_adq"));
                predio.setNotaria(resultSet.getString("chv_notaria"));
                predio.setFechaTituloProp(resultSet.getDate("dt_fecha_titulo_prop"));
                predio.setFechaRegistro(resultSet.getDate("dt_fecha_registro"));
                predio.setAreaEscritura(resultSet.getDouble("db_area_escritura"));
                predio.setProAnterior(resultSet.getString("chv_prop_anterior"));
                predio.setAvaluoPropi(resultSet.getDouble("db_avaluo_prop"));
                predio.setGestUsoSuelo(resultSet.getString("chv_gest_uso_suelo"));
                predio.setUsoSueloConsumo(resultSet.getString("chv_uso_suelo_consumo"));
                predio.setUsoSueloIntercambio(resultSet.getString("chv_us_suel_intercambio"));
                predio.setUsoSueloProduc(resultSet.getString("chv_us_suel_produc"));
                predio.setOcupacionPredio(resultSet.getString("chv_ocupacion_predio"));
                predio.setLocalizacionPredio(resultSet.getString("chv_localizacion_predio"));
                predio.setTopografiaPredio(resultSet.getString("chv_topografia_pedio"));
                predio.setFormaPredio(resultSet.getString("chv_forma_predio"));
                predio.setCaracteristicasSuelo(resultSet.getString("chv_caract_suelo"));
                predio.setUsoVias(resultSet.getString("chv_uso_vias"));
                predio.setMaterialVia(resultSet.getString("chv_material_vias"));
                predio.setRedAgua(resultSet.getString("chv_red_agua"));
                predio.setAlcantarillado(resultSet.getString("chv_alcantarillado"));
                predio.setEnergiaElectrica(resultSet.getString("chv_energ_electric"));
                predio.setRedTelefono(resultSet.getString("chv_red_telefon"));
                predio.setRecoleBasura(resultSet.getString("chv_rec_basura"));
                predio.setTransportePublico(resultSet.getString("chv_transp_publico"));
                predio.setInternet(resultSet.getString("chv_internet"));
                predio.setOtrosServicios(resultSet.getString("chv_otros_servicios"));
                predio.setAreaConstruccion(resultSet.getDouble("db_area_construc"));
                predio.setAreaTotalConstruccion(resultSet.getDouble("db_area_total_const"));
                predio.setAreaTotalTerreno(resultSet.getDouble("db_area_total_terreno"));
                predio.setPatio(resultSet.getString("chv_patio"));
                predio.setPiscina(resultSet.getString("chv_piscina"));
                predio.setCerramiento(resultSet.getString("chv_cerramiento"));
                predio.setCisterna(resultSet.getString("chv_cisterna"));
                predio.setMuros(resultSet.getString("chv_muros"));
                predio.setAscensor(resultSet.getString("chv_ascensor"));
                predio.setNumBanios(resultSet.getInt("int_num_banios"));
                predio.setLinderoFrente1(resultSet.getDouble("db_lindero_frente1"));
                predio.setLinderoFrente2(resultSet.getDouble("db_lindero_frente2"));
                predio.setLinderoFrente3(resultSet.getDouble("db_lindero_frente3"));
                predio.setLinderoFrente4(resultSet.getDouble("db_lindero_frente4"));
                predio.setLinderoCalle1(resultSet.getString("chv_lindero_calle1"));
                predio.setLinderoCalle2(resultSet.getString("chv_lindero_calle2"));
                predio.setLinderoCalle3(resultSet.getString("chv_lindero_calle3"));
                predio.setLinderoCalle4(resultSet.getString("chv_lindero_calle4"));
                predio.setLinderoAlicuota1(resultSet.getDouble("db_lindero_alicuota1"));
                predio.setLinderoAlicuota2(resultSet.getDouble("db_lindero_alicuota2"));
                predio.setLinderoAlicuota3(resultSet.getDouble("db_lindero_alicuota3"));
                predio.setLinderoAlicuota4(resultSet.getDouble("db_lindero_alicuota4"));
                predio.setDerechosAcciones(resultSet.getDouble("db_derechos_acciones"));
                predio.setCroquis(resultSet.getString("chv_croquis"));
                predio.setEmplazamiento(resultSet.getString("chv_emplazamiento"));
                predio.setFotografia(resultSet.getString("chv_fotografia"));
                predio.setTopografiaRefTop(resultSet.getString("chv_topografia_ref_top"));
                predio.setFotoAerea(resultSet.getString("chv_foto_aerea"));
                predio.setOtraRefTopo(resultSet.getString("chv_otra_ref_top"));
                predio.setCoordE(resultSet.getDouble("db_coord_e"));
                predio.setCoordN(resultSet.getDouble("db_coord_n"));
                predio.setColindanteNorte(resultSet.getString("chv_colindant_nort"));
                predio.setColindanteEste(resultSet.getString("chv_colindant_este"));
                predio.setColindanteSur(resultSet.getString("chv_colindant_sur"));
                predio.setColindanteOeste(resultSet.getString("chv_colindant_oest"));
                predio.setFuenteInformacion(resultSet.getString("chv_fuente_informant"));
                predio.setTelefoInformacion(resultSet.getString("chv_telf_informant"));
                predio.setFichaAdjunta(resultSet.getString("chv_ficha_adjunta"));
                predio.setFechaRegistrada(resultSet.getTimestamp("ts_fecha_registro"));
                predio.setFechaActualizacion(resultSet.getTimestamp("ts_fecha_actualizacion"));
                predio.setFechaBaja(resultSet.getTimestamp("ts_fecha_baja"));
                predio.setEstadoLogico(resultSet.getString("ch_estado_logico"));
                predio.setPorcentaExcepsion(resultSet.getDouble("db_porcent_excep"));
                predio.setExcepsionEsp(resultSet.getString("chv_excencion_esp"));
                predio.setObservaciones(resultSet.getString("chv_observaciones"));
                predio.setSectorHomogeneo(resultSet.getInt("id_sector_homogeneo"));
                predio.setUsuarioSistema(ServiciosUsuario.buscarUsuarioDadoId(resultSet.getInt("id_session_usuario")));
                predio.setFechaModificacion(resultSet.getTimestamp("ts_fecha_creacion"));
                predio.setHoraModificacion(resultSet.getTime("tm_hora_creacion"));
                predio.setAccionRealizada(resultSet.getString("chv_accion_realizada"));
                lst.add(predio);   
            }
        } catch (Exception e) {
            throw e;
        }
        return lst;
    }
}
